### ISSUE TITLE
Docker doesn't always install the latest version of WordPress

### ISSUE THREAD

**Issue by johannadevos** [Yoast/plugin-development-docker#17]
When Docker installs WordPress in `start.sh`, you don't always end up with the latest version of WordPress. Today, I got 5.3.2 whereas 5.4 is the latest. According to @herregroen, this could be because Docker does a lot of caching. Potentially a `docker pull` should be added.

**Comment by herregroen** [comment]
@Djennez Any chance you could take a look at this one?

I expect if the base image already exists locally then Docker will use that to build our image and won't check if there's a newer one.

**Comment by Djennez** [comment]
Can do. Do we also want to look at finding a way to get the latest WP (master / trunk) in an installation?
