### ISSUE TITLE
Change prefix of WordPress tables

### ISSUE THREAD

**Issue by jdevalk** [Yoast/plugin-development-docker#55]
By default the WordPress installs in our docker use `wp_`. I'd like to change that to a randomized string of 5 a-z chars, followed by an `_`, where it's different in each new docker install. This way people can't hardcode `wp_` in queries and get it to work :)

**Comment by noud-github** [comment]
moved to jira:
https://yoast.atlassian.net/jira/software/projects/DO/boards/13?selectedIssue=DO-527
