### ISSUE TITLE
Consider to add WPSEO_DEBUG to the WP config files

### ISSUE THREAD

**Issue by afercia** [Yoast/plugin-development-docker#6]
User case:
In order to easily debug the Schema output on the front end, I had to manually add `define( 'WPSEO_DEBUG', true );` to the `config/basic-wordpress-config.php`.

Of course this gave me a modified file and it's just a temporary workaround as I then need to revert the change each time.

I guess there are other cases where we'd want to have `WPSEO_DEBUG'` on. After all, the Docker sites are a development environment where debugging is a constant need.

Not sure if any drawbacks.

**Comment by Djennez** [comment]
Done. Add `?yoastdebug` to the URL to trigger yoast debugging.
